# -*- coding: utf-8 -*-
"""E mail_Spam_Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ohi9zzlegySY8AW67nSixHwBpVRKJEV0
"""

import numpy as np

import pandas as pd

df = pd.read_csv('/content/spam.csv', encoding='latin1')

df

df.info()

df.head()

df.drop(['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], axis=1,inplace=True)

df

import matplotlib.pyplot as plt

import seaborn as sns

df['v1'].value_counts()

df['v1'].value_counts().index

df['v1'].value_counts().index

df['v1'].value_counts().values

label_df=df['v1'].value_counts().index

value_df=df['v1'].value_counts().values

plt.pie(labels=label_df,x=value_df,autopct='%1.2f%%')

from sklearn.feature_extraction.text import CountVectorizer

vectorizer= CountVectorizer()

X=vectorizer.fit_transform(df['v2'])

X

X.shape

"""SMOTE"""

from imblearn.over_sampling import SMOTE
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

sm = SMOTE(random_state=42)

y=df['v1']

X_res,y_res = sm.fit_resample(X,y)

X_res

le=LabelEncoder()

y_res=le.fit_transform(y_res)

X_res_train, X_res_test, y_res_train, y_res_test = train_test_split(X_res, y_res, test_size=0.2, random_state=42)

from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB()
clf.fit(X_train, y_train)

y_pred=clf.predict(X_test)

y_pred

from sklearn.metrics import accuracy_score

accuracy_score(y_test,y_pred)

from sklearn.metrics import confusion_matrix

confusion_matrix(y_test,y_pred)

sns.heatmap(confusion_matrix(y_test,y_pred),annot = True)

from sklearn.metrics import classification_report

print(classification_report(y_test,y_pred))

